<a href="https://colab.research.google.com/github/kfartem434-png/MN_Kapusta/blob/main/%D0%9B%D0%A01_%D0%9A%D0%B0%D0%BF%D1%83%D1%81%D1%82%D0%B0_3_12.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Був присутній на парі

# Лабораторна робота 1. NumPy

**Тема:** основи роботи з бібліотекою NumPy, масиви, вектори та матриці.

### Правила роботи
- Виконуйте завдання послідовно.
- Для обчислень використовуйте можливості **NumPy**.
- Не замінюйте операції NumPy звичайними Python-циклами, якщо це прямо не вказано в умові.
- Після виконання кожного завдання виводьте отриманий результат.


## 0. Підготовка середовища

### Завдання 0
Імпортуйте бібліотеку NumPy з псевдонімом `np`. Виведіть версію встановленої бібліотеки NumPy.

In [11]:
# Код студента
import numpy as np
print(np.version.full_version)

2.1.3


## 1. Створення масивів NumPy

### Завдання 1
Створіть одновимірний NumPy-масив із чисел:
`[2, 4, 6, 8, 10]`.

Виведіть масив та його тип за допомогою `type()`.

In [12]:
# Код студента
array = np.array([2,4,6,8,10])

print("Масив: \n",array)
print("Тип масиву: \n",type(array))

Масив: 
 [ 2  4  6  8 10]
Тип масиву: 
 <class 'numpy.ndarray'>


### Завдання 2
Створіть:
1. масив із 10 нулів;
2. масив із 8 одиниць;
3. масив із 6 елементів, усі значення яких дорівнюють `7`.

Використайте відповідні функції NumPy.

In [21]:
# Код студента
zeros = np.zeros(10)
ones = np.ones(8)
sevens = np.full(6,7)

print("10 нулів: \n",zeros)
print("8 одиниць: \n",ones)
print("6 сімок: \n",sevens)

10 нулів: 
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
8 одиниць: 
 [1. 1. 1. 1. 1. 1. 1. 1.]
6 сімок: 
 [7 7 7 7 7 7]


### Завдання 3
Створіть масив цілих чисел від `1` до `20` включно.

Після цього створіть окремий масив парних чисел від `2` до `20`.

In [23]:
# Код студента
integers20 = np.arange(1,21)
evens20 = np.arange(2,21,2)

print("Цілі числа від 1 до 20: \n",integers20)
print("Парні числа від 1 до 20: \n",evens20)

Цілі числа від 1 до 20: 
 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
Парні числа від 1 до 20: 
 [ 2  4  6  8 10 12 14 16 18 20]


### Завдання 4
За допомогою `np.linspace()` створіть масив із **11 рівновіддалених чисел** від `0` до `1` включно.

In [22]:
# Код студента
one_lin = np.linspace(0,1,num=11)

print("11 рівновіддалених чисел від 0 до 1: \n",one_lin)

11 рівновіддалених чисел від 0 до 1: 
 [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]


### Завдання 5
Створіть матрицю розміром `3 × 4`, заповнену числами від `1` до `12`.

Спочатку створіть одновимірний масив, а потім змініть його форму.

In [25]:
# Код студента
M = np.arange(1,13).reshape((3,4))

print("Матриця 3x4 чисел 1 до 12: \n",M)

Матриця 3x4 чисел 1 до 12: 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


## 2. Основні характеристики масивів

### Завдання 6
Для матриці, створеної у попередньому завданні, визначте та виведіть:
- кількість вимірів;
- форму;
- загальну кількість елементів;
- тип даних елементів.

Використайте атрибути `ndim`, `shape`, `size`, `dtype`.

In [27]:
# Код студента
print("Кількість вимірів: \n",M.ndim)
print("Форма: \n",M.shape)
print("Кількість елементів: \n",M.size)
print("Тип даних: \n",M.dtype)

Кількість вимірів: 
 2
Форма: 
 (3, 4)
Кількість елементів: 
 12
Тип даних: 
 int64


### Завдання 7
Створіть масив:
`[1.2, 3.5, 5.7, 7.9]`.

Перетворіть його елементи на цілі числа за допомогою `astype()` та виведіть новий масив.

In [28]:
# Код студента
float_array = np.array([1.2,3.5,5.7,7.9])
int_array = float_array.astype(np.int64)

print("Масив дійсних чисел: \n",float_array)
print("Масив цілих чисел: \n",int_array)

Масив дійсних чисел: 
 [1.2 3.5 5.7 7.9]
Масив цілих чисел: 
 [1 3 5 7]


## 3. Індексація та зрізи

### Завдання 8
Створіть масив:
`[10, 20, 30, 40, 50, 60, 70, 80]`.

Виведіть:
1. перший елемент;
2. останній елемент;
3. елементи з індексами від `2` до `5` включно;
4. кожен другий елемент.

In [31]:
# Код студента
array = np.arange(10,81,10)

print("Перший елемент: \n",array[0])
print("Останній елемент: \n",array[-1])
print("Елементи за індексами від 2 до 5: \n",array[2:6])
print("Кожен другий елемент: \n",array[::2])

Перший елемент: 
 10
Останній елемент: 
 80
Елементи за індексами від 2 до 5: 
 [30 40 50 60]
Кожен другий елемент: 
 [10 30 50 70]


### Завдання 9
Створіть матрицю:

```text
[[ 1,  2,  3,  4],
 [ 5,  6,  7,  8],
 [ 9, 10, 11, 12]]
```

Виведіть:
1. елемент `7`;
2. другий рядок;
3. третій стовпець;
4. підматрицю з останніх двох рядків і перших двох стовпців.

In [44]:
# Код студента
M = np.arange(1,13).reshape((3,4))

print("Елемент 7: \n",M[1,2])
print("Другий рядок: \n",M[1])
print("Третій стовпець: \n",M[:,2])
print("Підматриця: \n",M[1:3,0:2])

Елемент 7: 
 7
Другий рядок: 
 [5 6 7 8]
Третій стовпець: 
 [ 3  7 11]
Підматриця: 
 [[ 5  6]
 [ 9 10]]


### Завдання 10
Створіть масив чисел від `1` до `15`.

Замініть усі елементи з індексами від `5` до `9` включно на число `0`.

In [45]:
# Код студента
array = np.arange(1,16)
carray = array.copy()
carray[5:10] = 0

print("Масив до заміни: \n",array)
print("Масив після заміни: \n",carray)

Масив до заміни: 
 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
Масив після заміни: 
 [ 1  2  3  4  5  0  0  0  0  0 11 12 13 14 15]


## 4. Арифметичні операції та агрегатні функції

### Завдання 11
Створіть два масиви:

```python
a = [1, 2, 3, 4, 5]
b = [10, 20, 30, 40, 50]
```

Виконайте поелементно:
- додавання;
- віднімання;
- множення;
- ділення.

In [46]:
# Код студента
a = np.arange(1,6)
b = np.arange(10,51,10)

print("a + b = \n",a + b)
print("b - a = \n",b - a)
print("a * b = \n",a * b)
print("b / a = \n",b / a)

a + b = 
 [11 22 33 44 55]
b - a = 
 [ 9 18 27 36 45]
a * b = 
 [ 10  40  90 160 250]
b / a = 
 [10. 10. 10. 10. 10.]


### Завдання 12
Для масиву:

`[4, 8, 15, 16, 23, 42]`

обчисліть:
- суму;
- середнє значення;
- мінімум;
- максимум;
- медіану;
- стандартне відхилення.

In [52]:
# Код студента
array = np.array([4, 8, 15, 16, 23, 42])

print("Масив: \n",array)
print("Сума: \n",array.sum())
print("Середнє значення: \n",array.mean())
print("Мінімум: \n",array.min())
print("Максимум: \n",array.max())
print("Медіана: \n",np.median(array))
print("Стандартне відхилення: \n",array.std())

Масив: 
 [ 4  8 15 16 23 42]
Сума: 
 108
Середнє значення: 
 18.0
Мінімум: 
 4
Максимум: 
 42
Медіана: 
 15.5
Стандартне відхилення: 
 12.315302134607444


### Завдання 13
Створіть матрицю:

```text
[[1, 2, 3],
 [4, 5, 6],
 [7, 8, 9]]
```

Обчисліть:
1. суму всіх елементів;
2. суму по кожному стовпцю;
3. суму по кожному рядку;
4. середнє значення по кожному стовпцю.

In [54]:
# Код студента
M = np.arange(1,10).reshape((3,3))

print("Матриця: \n",M)
print("Сума всіх елементів: \n",M.sum())
print("Сума по стовпцях: \n",M.sum(axis=0))
print("Сума по рядках: \n",M.sum(axis=1))
print("Середнє по стовпцям: \n",M.mean(axis=0))

Матриця: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Сума всіх елементів: 
 45
Сума по стовпцях: 
 [12 15 18]
Сума по рядках: 
 [ 6 15 24]
Середнє по стовпцям: 
 [4. 5. 6.]


### Завдання 14
Для масиву чисел від `1` до `10` обчисліть:
- квадрат кожного елемента;
- квадратний корінь кожного елемента;
- натуральний логарифм кожного елемента.

Використайте функції NumPy.

In [57]:
# Код студента
array = np.arange(1,11)

print("Масив: \n",array)
print("Квадрати: \n",array**2)
print("Квадратні корені: \n",np.sqrt(array))
print("Натуральні логарифми: \n",np.log(array))

Масив: 
 [ 1  2  3  4  5  6  7  8  9 10]
Квадрати: 
 [  1   4   9  16  25  36  49  64  81 100]
Квадратні корені: 
 [1.         1.41421356 1.73205081 2.         2.23606798 2.44948974
 2.64575131 2.82842712 3.         3.16227766]
Натуральні логарифми: 
 [0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.94591015 2.07944154 2.19722458 2.30258509]


## 5. Логічні операції та фільтрація

### Завдання 15
Створіть масив:

`[3, 7, 12, 18, 21, 25, 30, 34]`

За допомогою булевої маски виведіть:
1. усі числа, більші за `15`;
2. усі парні числа;
3. числа в діапазоні від `10` до `30` включно.

In [59]:
# Код студента
array = np.array([3, 7, 12, 18, 21, 25, 30, 34])

print("Масив: \n",array)
print("Числа більші за 15: \n",array[15 < array])
print("Парні числа: \n",array[array % 2 == 0])
print("Числа в діпазоні [10,30]: \n",array[(10 <= array) & (array <= 30)])

Масив: 
 [ 3  7 12 18 21 25 30 34]
Числа більші за 15: 
 [18 21 25 30 34]
Парні числа: 
 [12 18 30 34]
Числа в діпазоні [10,30]: 
 [12 18 21 25 30]


### Завдання 16
Для масиву:

`[-5, 3, -2, 8, -1, 10, 0]`

замініть усі від’ємні значення на `0`.

Не використовуйте цикл `for`.

In [60]:
# Код студента
array = np.array([-5, 3, -2, 8, -1, 10, 0])
carray = array.copy()
carray[carray < 0] = 0

print("Оригінальний масив: \n",array)
print("Новий масив: \n",carray)

Оригінальний масив: 
 [-5  3 -2  8 -1 10  0]
Новий масив: 
 [ 0  3  0  8  0 10  0]


### Завдання 17
Створіть масив випадкових цілих чисел від `0` до `100` розміром `20`.

Порахуйте:
- скільки елементів більші за `50`;
- скільки елементів менші або дорівнюють `50`.

Для відтворюваності встановіть `np.random.seed(42)`.

In [67]:
# Код студента
np.random.seed(42)

array = np.random.randint(0,101,size=20)

print("Масив: \n",array)
print("Більше за 50: \n",(50 < array).sum())
print("Меньше або дорівнює 50: \n",(array <= 50).sum())

Масив: 
 [51 92 14 71 60 20 82 86 74 74 87 99 23  2 21 52  1 87 29 37]
Більше за 50: 
 12
Меньше або дорівнює 50: 
 8


## 6. Зміна форми та об'єднання масивів

### Завдання 18
Створіть масив чисел від `1` до `24`.

Перетворіть його:
1. у матрицю `4 × 6`;
2. у матрицю `6 × 4`;
3. у тривимірний масив форми `2 × 3 × 4`.

Після кожного перетворення виведіть `shape`.

In [70]:
# Код студента
array = np.arange(1,25)
print("Масив: \n",array)

A = array.reshape((4,6))
print("Після 1 перетворення: \n",A.shape)
print(A)

B = array.reshape((6,4))
print("Після 2 перетворення: \n",B.shape)
print(B)

C = array.reshape((2,3,4))
print("Після 3 перетворення: \n",C.shape)
print(C)

Масив: 
 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]
Після 1 перетворення: 
 (4, 6)
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]
Після 2 перетворення: 
 (6, 4)
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]
Після 3 перетворення: 
 (2, 3, 4)
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


### Завдання 19
Створіть дві матриці:

```text
A = [[1, 2],
     [3, 4]]

B = [[5, 6],
     [7, 8]]
```

Об’єднайте їх:
1. вертикально;
2. горизонтально.

Використайте функції NumPy.

In [69]:
# Код студента
A = np.array([[1, 2],[3, 4]])
B = np.array([[5, 6],[7, 8]])

V = np.vstack((A,B))
H = np.hstack((A,B))

print("Матриця A: \n",A)
print("Матриця B: \n",B)
print("Вертикально об'єднані: \n",V)
print("Горизонтально об'єднані: \n",H)

Матриця A: 
 [[1 2]
 [3 4]]
Матриця B: 
 [[5 6]
 [7 8]]
Вертикально об'єднані: 
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
Горизонтально об'єднані: 
 [[1 2 5 6]
 [3 4 7 8]]


### Завдання 20
Створіть матрицю `3 × 4` із числами від `1` до `12`.

Перетворіть її назад в одновимірний масив двома способами:
- за допомогою `flatten()`;
- за допомогою `ravel()`.

Порівняйте результати.

In [72]:
# Код студента
M = np.arange(1,13).reshape((3,4))

print("Матриця: \n",M)
print("Після flatten: \n",M.flatten())
print("Після ravel: \n",M.ravel())

Матриця: 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Після flatten: 
 [ 1  2  3  4  5  6  7  8  9 10 11 12]
Після ravel: 
 [ 1  2  3  4  5  6  7  8  9 10 11 12]


## 7. Дії з векторами

### Завдання 21
Дано два вектори:

```text
a = [2, 4, 6]
b = [1, 3, 5]
```

Знайдіть:
- суму векторів;
- різницю векторів;
- результат множення кожного вектора на число `3`.

In [73]:
# Код студента
a = np.array([2, 4, 6])
b = np.array([1, 3, 5])

print("a + b = \n",a + b)
print("a - b = \n",a - b)
print("a * 3 = \n",a * 3)
print("b * 3 = \n",b * 3)

a + b = 
 [ 3  7 11]
a - b = 
 [1 1 1]
a * 3 = 
 [ 6 12 18]
b * 3 = 
 [ 3  9 15]


### Завдання 22
Для векторів:

```text
a = [1, 2, 3]
b = [4, 5, 6]
```

Обчисліть їх **скалярний добуток** двома способами:
1. за допомогою `np.dot()`;
2. за допомогою оператора `@`.

In [77]:
# Код студента
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print("Скалярний добуток через np.dot: \n",np.dot(a,b))
print("Скалярний добуток через @: \n",a @ b)

Скалярний добуток через np.dot: 
 32
Скалярний добуток через @: 
 32


### Завдання 23
Для вектора:

```text
v = [3, 4]
```

обчисліть його евклідову норму.

Потім нормалізуйте вектор, тобто отримайте вектор одиничної довжини.

In [80]:
# Код студента
v = np.array([3, 4])
norm = np.linalg.norm(v)

print("Евклідова норма вектора: \n",norm)
print("Нормалізований вектор: \n",v / norm)

Евклідова норма вектора: 
 5.0
Нормалізований вектор: 
 [0.6 0.8]


### Завдання 24
Дано вектори:

```text
a = [1, 0, 0]
b = [0, 1, 0]
```

Знайдіть їх векторний добуток за допомогою `np.cross()`.

In [81]:
# Код студента
a = np.array([1, 0, 0])
b = np.array([0, 1, 0])

print("Векторний добуток a і b: \n",np.cross(a,b))

Векторний добуток a і b: 
 [0 0 1]


### Завдання 25
Дано два вектори:

```text
a = [1, 2]
b = [2, 1]
```

Обчисліть косинус кута між ними за формулою через скалярний добуток і норми векторів.

Додатково знайдіть сам кут у градусах.

In [102]:
# Код студента
a = np.array([1, 2])
b = np.array([2, 1])
a_norm = np.linalg.norm(a)
b_norm = np.linalg.norm(b)
vcosine = (np.dot(a,b))/(a_norm * b_norm)

print("Косинус кута між векторами: \n",vcosine)
print("Кут між векторами у градусах: \n",np.degrees(np.arccos(vcosine)))

Косинус кута між векторами: 
 0.7999999999999998
Кут між векторами у градусах: 
 36.86989764584404


## 8. Дії з матрицями

### Завдання 26
Дано матрицю:

```text
A = [[1, 2, 3],
     [4, 5, 6]]
```

Знайдіть транспоновану матрицю двома способами:
1. за допомогою `.T`;
2. за допомогою `np.transpose()`.

In [86]:
# Код студента
A = np.array(
    [[1, 2, 3],
     [4, 5, 6]]
)

print("Транспонована матриця через .T: \n",A.T)
print("Транспонована матриця через np.transpose: \n",np.transpose(A))

Транспонована матриця через .T: 
 [[1 4]
 [2 5]
 [3 6]]
Транспонована матриця через np.transpose: 
 [[1 4]
 [2 5]
 [3 6]]


### Завдання 27
Дано матриці:

```text
A = [[1, 2],
     [3, 4]]

B = [[2, 0],
     [1, 2]]
```

Обчисліть:
1. поелементний добуток `A * B`;
2. матричний добуток `A @ B`.

Поясніть у коментарі до коду, чим відрізняються ці операції.

In [87]:
# Код студента
A = np.array(
    [[1, 2],
     [3, 4]]
)
B = np.array(
    [[2, 0],
     [1, 2]]
)

# Поелементний добуток * перемножає відповідні елементи обох матриць
print("Поелементний добуток: \n",A * B)
# Матричний  добуток @ проводить матричне перемноження матриць (тобто скалярний добуток відповідних рядків та стовпців матриць)
print("Матричний добуток: \n",A @ B)

Поелементний добуток: 
 [[2 0]
 [3 8]]
Матричний добуток: 
 [[ 4  4]
 [10  8]]


### Завдання 28
Для матриці:

```text
A = [[4, 7],
     [2, 6]]
```

обчисліть:
- визначник;
- обернену матрицю.

Перевірте результат, помноживши початкову матрицю на обернену.

In [89]:
# Код студента
A = np.array(
    [[4, 7],
     [2, 6]]
)

print("Визначник матриці: \n",np.linalg.det(A))
print("Обернена матриця: \n",np.linalg.inv(A))
print("A @ A^-1 = \n",A @ np.linalg.inv(A))

Визначник матриці: 
 10.000000000000002
Обернена матриця: 
 [[ 0.6 -0.7]
 [-0.2  0.4]]
A @ A^-1 = 
 [[ 1.00000000e+00 -1.11022302e-16]
 [ 1.11022302e-16  1.00000000e+00]]


### Завдання 29
Розв’яжіть систему лінійних рівнянь за допомогою NumPy:

```text
2x +  y = 5
 x + 3y = 6
```

Сформуйте матрицю коефіцієнтів `A` і вектор правих частин `b`.

Використайте `np.linalg.solve()`.

In [90]:
# Код студента
A = np.array(
    [[2,1],
     [1,3]]
)
b = np.array([5,6])
solution = np.linalg.solve(A,b)

print("Розв'язок системи: \n",solution)

Розв'язок системи: 
 [1.8 1.4]


### Завдання 30
Створіть одиничну матрицю розміром `4 × 4`.

Перевірте властивість одиничної матриці: помножте на неї довільну матрицю `4 × 4` та порівняйте результат з початковою матрицею.

In [115]:
# Код студента
A = np.eye(4)
B = np.array(
    [[1,2,3,4],
     [2,4,6,8],
     [3,6,9,12],
     [4,8,12,16]]
)

print("Початкова матриця: \n",B)
print("Після множення на одиничну матрицю: \n",A @ B)

Початкова матриця: 
 [[ 1  2  3  4]
 [ 2  4  6  8]
 [ 3  6  9 12]
 [ 4  8 12 16]]
Після множення на одиничну матрицю: 
 [[ 1.  2.  3.  4.]
 [ 2.  4.  6.  8.]
 [ 3.  6.  9. 12.]
 [ 4.  8. 12. 16.]]


## 9. Broadcasting (операція трансляції)

### Завдання 31
Створіть матрицю:

```text
A = [[1, 2, 3],
     [4, 5, 6],
     [7, 8, 9]]
```

Додайте число `10` до кожного її елемента.

In [92]:
# Код студента
A = np.array(
    [[1, 2, 3],
     [4, 5, 6],
     [7, 8, 9]]
)

print("Початкова матриця: \n",A)
print("A + 10 = \n",A + 10)

Початкова матриця: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
A + 10 = 
 [[11 12 13]
 [14 15 16]
 [17 18 19]]


### Завдання 32
До матриці:

```text
A = [[1, 2, 3],
     [4, 5, 6],
     [7, 8, 9]]
```

додайте вектор:

```text
v = [10, 20, 30]
```

Проаналізуйте, як NumPy застосував broadcasting.

In [93]:
# Код студента
A = np.array(
    [[1, 2, 3],
     [4, 5, 6],
     [7, 8, 9]]
)
v = np.array([10, 20, 30])

print("A + v = \n",A + v)

A + v = 
 [[11 22 33]
 [14 25 36]
 [17 28 39]]


### Завдання 33
Нормалізуйте **кожен стовпець** матриці:

```text
A = [[10, 20, 30],
     [20, 30, 40],
     [30, 40, 50]]
```

за формулою:

\[
z = \frac{x - \mu}{\sigma}
\]

де `μ` — середнє значення стовпця, `σ` — стандартне відхилення стовпця.

Не використовуйте цикл `for`.

In [118]:
# Код студента
A = np.array(
    [[10, 20, 30],
     [20, 30, 40],
     [30, 40, 50]]
)
mean = np.mean(A,axis=0)
std = np.std(A,axis=0)

normalized = (A - mean)/std

print("Нормалізовані стовпці: \n",normalized)

Нормалізовані стовпці: 
 [[-1.22474487 -1.22474487 -1.22474487]
 [ 0.          0.          0.        ]
 [ 1.22474487  1.22474487  1.22474487]]


## 10. Випадкові дані

### Завдання 34
Встановіть `np.random.seed(42)` та створіть:
1. 10 випадкових цілих чисел від `1` до `100`;
2. матрицю `3 × 3` випадкових чисел від `0` до `1`;
3. 1000 значень із нормального розподілу.

Для третього масиву обчисліть середнє та стандартне відхилення.

In [119]:
# Код студента
np.random.seed(42)

integers = np.random.randint(1,101,size=10)
M = np.random.rand(3,3)
normal = np.random.normal(size=1000)

print("10 випадкових цілих чисел від 1 до 100: \n",integers)
print("Матриця 3x3 випадкових чисел від 0 до 1: \n",M)
print("Середнє нормального розподілу: \n",normal.mean())
print("Стандартне відхилення нормального розподілу: \n",normal.std())

10 випадкових цілих чисел від 1 до 100: 
 [52 93 15 72 61 21 83 87 75 75]
Матриця 3x3 випадкових чисел від 0 до 1: 
 [[0.86617615 0.60111501 0.70807258]
 [0.02058449 0.96990985 0.83244264]
 [0.21233911 0.18182497 0.18340451]]
Середнє нормального розподілу: 
 0.02216865975826456
Стандартне відхилення нормального розподілу: 
 0.9792284455184356


### Завдання 35
Змоделюйте оцінки 30 студентів — випадкові цілі числа від `0` до `100`.

Визначте:
- середню оцінку;
- медіану;
- найвищу та найнижчу оцінки;
- кількість студентів, які отримали не менше `60`;
- відсоток студентів, які отримали не менше `90`.

In [123]:
# Код студента
np.random.seed(42)

grades = np.random.randint(1,101,size=30)

print("Оцінки: \n",grades)
print("Середня оцінка: \n",grades.mean())
print("Медіанна оцінка: \n",np.median(grades))
print("Найнижча оцінка: \n",grades.min())
print("Найвища оцінка: \n",grades.max())
print("Кількість студентів не нижче за 60: \n",(60 <= grades).sum())
print("Відсоток студентів не нижче за 90: \n",(90 <= grades).mean() * 100)

Оцінки: 
 [ 52  93  15  72  61  21  83  87  75  75  88 100  24   3  22  53   2  88
  30  38   2  64  60  21  33  76  58  22  89  49]
Середня оцінка: 
 51.86666666666667
Медіанна оцінка: 
 55.5
Найнижча оцінка: 
 2
Найвища оцінка: 
 100
Кількість студентів не нижче за 60: 
 14
Відсоток студентів не нижче за 90: 
 6.666666666666667


## 11. Підсумкові завдання

### Завдання 36
Дано результати продажів трьох товарів за чотири місяці:

```text
sales = [[120, 150, 170, 160],
         [80,  90,  100, 110],
         [200, 180, 210, 230]]
```

Рядки — товари, стовпці — місяці.

Визначте:
1. загальний обсяг продажів кожного товару;
2. загальний обсяг продажів у кожному місяці;
3. товар із найбільшими сумарними продажами;
4. місяць із найбільшим загальним обсягом продажів;
5. середній обсяг продажів кожного товару.

In [100]:
# Код студента
sales = np.array(
    [[120, 150, 170, 160],
     [80,  90,  100, 110],
     [200, 180, 210, 230]]
)

print(" \n",sales.sum(axis=1))
print(" \n",sales.sum(axis=0))
print(" \n",sales.sum(axis=1).max())
print(" \n",sales.sum(axis=0).max())
print(" \n",sales.mean(axis=1))

 
 [600 380 820]
 
 [400 420 480 500]
 
 820
 
 500
 
 [150.  95. 205.]


### Завдання 37
Створіть квадратну матрицю `5 × 5` із випадкових цілих чисел від `1` до `20`.

Виконайте:
1. знайдіть суму головної діагоналі;
2. знайдіть суму побічної діагоналі;
3. знайдіть максимальний елемент кожного рядка;
4. знайдіть мінімальний елемент кожного стовпця;
5. замініть усі елементи, менші за середнє значення всієї матриці, на `0`.

In [129]:
# Код студента
np.random.seed(42)

A = np.random.randint(1,21,size=25).reshape(5,5)

print("Матриця: \n",A)
print("Сума головної діагоналі: \n",A.trace())
print("Сума побічної діагоналі: \n",np.diag(np.fliplr(A)).sum())
print("Максимальний елемент кожного рядка: \n",A.max(axis=1))
print("Мінімальний елемент кожного стовпця: \n",A.min(axis=0))
print("Замінені елементи: \n",A * (A >= A.mean()))

Матриця: 
 [[ 7 20 15 11  8]
 [ 7 19 11 11  4]
 [ 8  3  2 12  6]
 [ 2  1 12 12 17]
 [10 16 15 15 19]]
Сума головної діагоналі: 
 59
Сума побічної діагоналі: 
 32
Максимальний елемент кожного рядка: 
 [20 19 12 17 19]
Мінімальний елемент кожного стовпця: 
 [ 2  1  2 11  4]
Замінені елементи: 
 [[ 0 20 15 11  0]
 [ 0 19 11 11  0]
 [ 0  0  0 12  0]
 [ 0  0 12 12 17]
 [ 0 16 15 15 19]]


### Завдання 38
Дано матрицю ознак трьох об’єктів:

```text
X = [[2, 4, 6],
     [1, 3, 5],
     [5, 7, 9]]
```

Обчисліть **евклідову відстань** між:
- першим і другим рядком;
- першим і третім рядком;
- другим і третім рядком.

Використайте операції NumPy та `np.linalg.norm()`.

In [133]:
# Код студента
X = np.array(
    [[2, 4, 6],
     [1, 3, 5],
     [5, 7, 9]]
)

norm_1_2 = np.linalg.norm((X[0,:],X[1,:]))
norm_1_3 = np.linalg.norm((X[0,:],X[2,:]))
norm_2_3 = np.linalg.norm((X[1,:],X[2,:]))

print("Евклідова відстань між 1 та 2 рядком: \n",norm_1_2)
print("Евклідова відстань між 1 та 3 рядком: \n",norm_1_3)
print("Евклідова відстань між 2 та 3 рядком: \n",norm_2_3)

Евклідова відстань між 1 та 2 рядком: 
 [2 4 6]
Евклідова відстань між 1 та 3 рядком: 
 14.52583904633395
Евклідова відстань між 2 та 3 рядком: 
 13.784048752090222


### Завдання 39
Створіть матрицю `4 × 4` із довільних цілих чисел.

Для кожного рядка знайдіть його норму та створіть нову матрицю, у якій кожен рядок нормалізований до одиничної довжини.

Спробуйте виконати завдання без циклів.

In [136]:
# Код студента
M = np.array(
    [[1,2,1,2],
     [3,4,3,4],
     [5,6,5,6],
     [7,8,7,8]]
)
noramlized_M = M / np.linalg.norm(M,axis=0)

print("Нормалізовані рядки: \n",noramlized_M)

Нормалізовані рядки: 
 [[0.10910895 0.18257419 0.10910895 0.18257419]
 [0.32732684 0.36514837 0.32732684 0.36514837]
 [0.54554473 0.54772256 0.54554473 0.54772256]
 [0.76376262 0.73029674 0.76376262 0.73029674]]


### Завдання 40
Створіть матрицю коефіцієнтів і вектор правих частин для системи:

```text
 x + 2y +  z =  9
2x +  y -  z =  8
3x -  y + 2z =  3
```

1. Розв’яжіть систему за допомогою `np.linalg.solve()`.
2. Перевірте знайдений розв’язок матричним множенням `A @ x`.
3. Порівняйте результат із вектором `b`.

In [137]:
# Код студента
A = np.array(
    [[1, 2, 1],
     [2, 1,-1],
     [3,-1, 2]]
)
b = np.array([9,8,3])

solution = np.linalg.solve(A,b)

print("Матричне множення: \n",A @ solution)
print("Порівняння з вектором b: \n",np.allclose(A @ solution,b))

Матричне множення: 
 [9. 8. 3.]
Порівняння з вектором b: 
 True


---

## Самоперевірка

Після виконання роботи студент повинен уміти:
- створювати та перетворювати NumPy-масиви;
- використовувати індексацію та зрізи;
- виконувати векторизовані арифметичні операції;
- застосовувати агрегатні функції;
- використовувати булеві маски;
- змінювати форму та об'єднувати масиви;
- виконувати основні дії з векторами;
- виконувати основні операції з матрицями;
- застосовувати broadcasting;
- використовувати функції `numpy.linalg` для задач лінійної алгебри.
